const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const AppSchema = new Schema({
  trackId: { type: Number, required: [true, 'trackId is required.'] },
  trackName: String,
  trackCensoredName: String,
  trackViewUrl: String,
  // developer: {
  //   type: Schema.Types.ObjectId,
  //   ref: 'developer',
  // },
  artistId: Number,
  artistName: String,
  artistViewUrl: String,
  sellerName: String,
  sellerUrl: String,
  artworkUrl60: String,
  artworkUrl100: String,
  artworkUrl512: String,
  screenshotUrls: Array,
  ipadScreenshotUrls: Array,
  appletvScreenshotUrls: Array,
  price: Number,
  formattedPrice: String,
  currency: String,
  fileSizeBytes: String,
  version: String,
  currentVersionReleaseDate: String,
  releaseDate: String,
  releaseNotes: String,
  description: String,
  averageUserRating: Number,
  userRatingCount: Number,
  averageUserRatingForCurrentVersion: Number,
  userRatingCountForCurrentVersion: Number,
  bundleId: String,
  primaryGenreId: Number,
  primaryGenreName: String,
  // categories: [{
  //   type: Schema.Types.ObjectId,
  //   ref: 'category',
  // }],
  genres: Array,
  genreIds: Array,
  genreList: Array,
  kind: String,
  wrapperType: String,
  minimumOsVersion: String,
  trackContentRating: String,
  contentAdvisoryRating: String,
  isGameCenterEnabled: Boolean,
  isVppDeviceBasedLicensingEnabled: Boolean,
  features: Array,
  supportedDevices: Array,
  advisories: Array,
  languageCodesISO2A: Array,
});

const App = mongoose.model('app', AppSchema);

module.exports = App;
